%% DOCUMENTATION
%
% AUTHOR: Katie Lavigne (lavigne.k@gmail.com)
% DATE: June 17th, 2016
% 
% FILE:     chkactive.m
% PURPOSE:  Activate relevant GUI buttons and checkboxes.
% USAGE:    Runs automatically from eegGUI.m after each step
% 
% DESCRIPTION: This script checks if relevant *.set files exist in the
% user-defined processing directory and activates/deactivates the corresponding 
% buttons/checkboxes in the EEG GUI. Works for PC and Linux.

function chkactive(handles, hObject)
set([handles.datasetup, handles.quit], 'enable', 'on');
datasetup_vals = getappdata(0,'datasetup_vals');
if isempty(datasetup_vals)
    return
end
if ~strcmp(datasetup_vals.datadir, 'No Directory Selected!') ...
        && size(datasetup_vals.subjs,1) > 0 ...
        && ~strcmp(datasetup_vals.savedir, 'No Directory Selected!')
    set([handles.reexporttxt, handles.exportEEGevents, handles.syncEEGtiming], 'enable', 'on');
else
    set([handles.reexporttxt, handles.exportEEGevents, handles.syncEEGtiming], 'enable', 'off');
end

set([handles.plotraw, handles.plotfiltered, handles.plotbins, handles.plotepochs, handles.plotepchrej],'Value',0);
set([handles.plot,  ...
    handles.plotraw, ...
    handles.chaninfo_rflag, ...
    handles.filter_rflag, ...
    handles.reref_rflag, ...
    handles.bins_rflag, ...
    handles.epochs_rflag, ...
    handles.run, ...
    handles.plotfiltered, ...
    handles.plotbins, ...
    handles.plotepochs, ...
    handles.rmchan_man, ...
    handles.rmchan_auto, ...
    handles.epchrej_man, ...
    handles.epchrej_auto, ...
    handles.runica, ...
    handles.limitcomps, ...
    handles.rejepchs, ...
    handles.chan_interp, ...
    handles.plotepchrej, ...
    handles.plotICAcomps], 'enable', 'off');
guidata(hObject, handles);

if ~strcmp(datasetup_vals.savedir, 'No Directory Selected!')
    args = {datasetup_vals.savedir, handles, hObject};
    Recurse_Files(args, 'isActive');
    
end